# This module defines
#  TINYXML_FOUND, if false, do not try to link
#  TINYXML_LIBRARY, the library to link against
#  TINYXML_INCLUDE_DIR, where to find headers


FIND_PATH(TINYXML_INCLUDE_DIR tinyxml.h
  PATHS
  $ENV{TINYXML_DIR}
  PATH_SUFFIXES include
)

FIND_LIBRARY(TINYXML_LIBRARY
  NAMES tinyxml
  PATHS
  $ENV{TINYXML_DIR}
  PATH_SUFFIXES lib
)

IF(TINYXML_LIBRARY AND TINYXML_INCLUDE_DIR)
  SET(TINYXML_FOUND "YES")
  SET(TINYXML_LIBRARIES ${TINYXML_LIBRARY})
ENDIF()