name: On Push

on: [push]

jobs:
  build:
    name: Push
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
    uses: ./.github/workflows/build.yml
    with:
      os: ${{ matrix.os }}